### ISSUE TITLE
hexo install 总是一大堆错误，各种Cannot find module

### ISSUE THREAD

**Issue by mwlgcmwlgc** [hexojs/site#155]
```
$ hexo install
ERROR Script load failed: scripts\helpers.js
Error: Cannot find module 'htmlparser2'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\cheerio\lib\parse.j                                                                                        s:4:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\cheerio\lib\cheerio                                                                                        .js:5:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\cheerio\index.js:5:                                                                                        28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Work\GitCafe\site\scripts\helpers.js:6:15
    at D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\n                                                                                        ode_modules\bluebird\js\release\util.js:11:23)
ERROR Plugin load failed: hexo-renderer-jade
Error: Cannot find module 'character-parser'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-jade\                                                                                        node_modules\jade\lib\lexer.js:4:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-jade\                                                                                        node_modules\jade\lib\parser.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-jade\                                                                                        node_modules\jade\lib\index.js:13:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Work\GitCafe\site\node_modules\hexo-renderer-jade\index.js:1:77
    at D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\n                                                                                        ode_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (D:\Work\GitCafe\site\node_modules\hexo                                                                                        \node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (D:\Work\GitCafe\site\node_modules\hexo\node_modul                                                                                        es\hexo-fs\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hex                                                                                        o-fs\node_modules\bluebird\js\release\promise.js:617:18)
    at Promise._resolveCallback (D:\Work\GitCafe\site\node_modules\hexo\node_mod                                                                                        ules\hexo-fs\node_modules\bluebird\js\release\promise.js:418:57)
    at Promise._settlePromiseFromHandler (D:\Work\GitCafe\site\node_modules\hexo                                                                                        \node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:504:17)
    at Promise._settlePromise (D:\Work\GitCafe\site\node_modules\hexo\node_modul                                                                                        es\hexo-fs\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hex                                                                                        o-fs\node_modules\bluebird\js\release\promise.js:617:18)
    at D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\node_modules\                                                                                        bluebird\js\release\nodeback.js:42:21
ERROR Plugin load failed: hexo-renderer-marked
Error: Cannot find module 'highlight.js/lib/highlight'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-marke                                                                                        d\node_modules\hexo-util\lib\highlight.js:3:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-marke                                                                                        d\node_modules\hexo-util\lib\index.js:8:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-marke                                                                                        d\lib\renderer.js:6:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Work\GitCafe\site\node_modules\hexo-renderer-marked\index.js:5:16
    at D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\n                                                                                        ode_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (D:\Work\GitCafe\site\node_modules\hexo                                                                                        \node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (D:\Work\GitCafe\site\node_modules\hexo\node_modul                                                                                        es\hexo-fs\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hex                                                                                        o-fs\node_modules\bluebird\js\release\promise.js:617:18)
    at Promise._resolveCallback (D:\Work\GitCafe\site\node_modules\hexo\node_mod                                                                                        ules\hexo-fs\node_modules\bluebird\js\release\promise.js:418:57)
    at Promise._settlePromiseFromHandler (D:\Work\GitCafe\site\node_modules\hexo                                                                                        \node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:504:17)
    at Promise._settlePromise (D:\Work\GitCafe\site\node_modules\hexo\node_modul                                                                                        es\hexo-fs\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hex                                                                                        o-fs\node_modules\bluebird\js\release\promise.js:617:18)
    at D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\node_modules\                                                                                        bluebird\js\release\nodeback.js:42:21
ERROR Plugin load failed: hexo-renderer-stylus
Error: Cannot find module './nodes'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\node_modules\stylus\lib\lexer.js:13:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\node_modules\stylus\lib\parser.js:11:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\node_modules\stylus\lib\renderer.js:12:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\node_modules\stylus\lib\stylus.js:11:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\node_modules\stylus\index.js:4:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-renderer-stylu                                                                                        s\lib\renderer.js:1:76)
ERROR Plugin load failed: hexo-server
Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-server\node_mo                                                                                        dules\connect\node_modules\debug\debug.js:14:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-server\node_mo                                                                                        dules\connect\node_modules\debug\node.js:15:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-server\node_mo                                                                                        dules\connect\index.js:16:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Work\GitCafe\site\node_modules\hexo-server\lib\ser                                                                                        ver.js:3:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Work\GitCafe\site\node_modules\hexo-server\index.js:21:4
    at D:\Work\GitCafe\site\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hexo-fs\n                                                                                        ode_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (D:\Work\GitCafe\site\node_modules\hexo                                                                                        \node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (D:\Work\GitCafe\site\node_modules\hexo\node_modul                                                                                        es\hexo-fs\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (D:\Work\GitCafe\site\node_modules\hexo\node_modu                                                                                        les\hexo-fs\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (D:\Work\GitCafe\site\node_modules\hexo\node_modules\hex                                                                                        o-fs\node_modules\bluebird\js\release\promise.js:617:18)
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
```

**Comment by Xuanwo** [comment]
并不理解`hexo install`是什么命令。。

**Comment by mwlgcmwlgc** [comment]
额(-__-)b，竟然搞错了。。。
