### ISSUE TITLE
WarehouseError: ID `themes` has been used

### ISSUE THREAD

**Issue by uiolee** [hexojs/site#2043]
when i multiple run `hexo g` or `hexo s`, errors occurs.

```shell
$ npx hexo g
...
...
INFO  1609 files generated in 7.11 s

$ npx hexo g
INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
WarehouseError: ID `themes` has been used
    at new WarehouseError (E:\site\node_modules\warehouse\dist\error.js:12:15)
    at _Model._insertOne (E:\site\node_modules\warehouse\dist\model.js:157:46)
    at E:\site\node_modules\warehouse\dist\model.js:179:78
    at tryCatcher (E:\site\node_modules\bluebird\js\release\util.js:16:23)
    at E:\site\node_modules\bluebird\js\release\using.js:185:26
    at tryCatcher (E:\site\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\site\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\site\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\site\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\site\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (E:\site\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (E:\site\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (E:\site\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (E:\site\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (E:\site\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\site\node_modules\bluebird\js\release\promise.js:729:18)
```

<details><summary>version details</summary>
<p>

```shell
$ node -v
v18.16.1

$ npm list
hexo-site@0.0.0 E:\site
├── cheerio@0.22.0
├── eslint-config-hexo@5.0.0
├── eslint@8.46.0
├── hexo-clean-css@2.0.0
├── hexo-filter-nofollow@2.0.2
├── hexo-fs@4.1.1
├── hexo-generator-archive@2.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-sitemap@3.0.1
├── hexo-renderer-marked@6.1.1
├── hexo-renderer-pug@3.0.0
├── hexo-renderer-stylus@3.0.0
├── hexo-server@3.0.0
├── hexo-tag-embed@1.0.0-rc.1
├── hexo-uglify@2.0.0
├── hexo@7.0.0-rc1
├── husky@8.0.3
├── imagemin-lint-staged@0.5.1
├── lint-staged@13.2.3
├── lunr@2.3.9
└── sharp@0.32.4
```

</p>
</details>

**Comment by stevenjoezhang** [comment]
Caused by https://github.com/hexojs/site/blob/4c0920dbce47b2385f13d5f51ec8480257c7cff3/scripts/data.js#L18
I'll try to fix it later
