### ISSUE TITLE
[Question]: Unhandled rejection TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Gabirel** [hexojs/site#491]
I am using [scripts/helper.js](https://github.com/hexojs/site/blob/master/scripts/helpers.js) to help me accomplish something I want.

But it always failed, saying `Unhandled rejection TypeError: Cannot read property 'name' of undefined`

'name' is : https://github.com/hexojs/site/blob/master/scripts/helpers.js#L147
Here's the log:
```js
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (/home/gabriel/Documents/git_project/Gabirel.github.io/scripts/helpers.js:147:14)
    at wrapper (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._lodash@4.17.4@lodash/lodash.js:4968:19)
    at Object.eval [as tpl] (eval at precompile (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:498:13), <anonymous>:7:127)
    at compiled (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:619:18)
    at Object.eval [as tpl] (eval at precompile (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:498:13), <anonymous>:95:173)
    at compiled (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:619:18)
    at Object.eval [as tpl] (eval at precompile (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:498:13), <anonymous>:736:163)
    at compiled (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._swig@1.4.2@swig/lib/swig.js:619:18)
    at Theme._View.View._compiled (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._hexo@3.3.7@hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._hexo@3.3.7@hexo/lib/theme/view.js:29:15)
    at /home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._hexo@3.3.7@hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._bluebird@3.5.0@bluebird/js/release/util.js:16:23)
    at /home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._bluebird@3.5.0@bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/gabriel/Documents/git_project/Gabirel.github.io/node_modules/._hexo@3.3.7@hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:350:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

I do have the file: `source/_data/languages.yml`
```yml
en: English
zh-tw:
  name: 正體中文
  disqus_lang: zh_TW
zh-cn:
  name: 简体中文
  disqus_lang: zh
```

**Comment by NoahDragon** [comment]
en doesn't have any name property under it.

**Comment by Gabirel** [comment]
@NoahDragon Actually, I do have a property called name: `source/_data/languages.yml`
As you can see below:
```yml
en: English
zh-tw:
  name: 正體中文
  disqus_lang: zh_TW
zh-cn:
  name: 简体中文
  disqus_lang: zh
```

**Comment by Gabirel** [comment]
Oh, I know.

My theme's language value is different from hexo's site.
`Hello-world.md`:
![image](https://cloud.githubusercontent.com/assets/12933851/26415824/5f2417be-40e6-11e7-800f-0cb3d1095dc9.png)

So, I changed the `languages.yml`:

![image](https://cloud.githubusercontent.com/assets/12933851/26415858/7c803a72-40e6-11e7-9bcb-f389f4f13188.png)

Then, it has values. Thanks @NoahDragon
